### ISSUE TITLE
Mean and variance reshaping

### ISSUE THREAD

**Issue by EricElmoznino** [0zgur0/conditional_batch_normalization#1]
I do not believe that these lines will compute the mean and variance in a channel-major way
```
# Mini-batch mean
mean = torch.mean(input.view(C,-1), dim=1)
# Mini-batch variance
variance = torch.mean(((input - mean.view(1,C,1,1).expand((N, C, H, W))) ** 2).view(C,-1), dim=1)
```
because the reshaping happens when the input is batch-major.

I think the code below would work as intended
```
# Mini-batch mean and variance
input_channel_major = input.permute(1, 0, 2, 3).contiguous().view(C -1)
mean = input_channel_major.mean(dim=1)
variance = input_channel_major.var(dim=1)
```

**Comment by 0zgur0** [comment]
Yes, that is true! It did not work out as expected in my project and I was planning to review the code! Thanks for pointing out the error:)
